; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

; ضبط سرعة السيريال (مهمة للتواصل مع الـ STM32)
monitor_speed = 115200

; تسريع عملية رفع الكود للقطعة
upload_speed = 921600

; المكتبات المطلوبة
lib_deps =
    Links2004/WebSockets @ ^2.4.1